# Generated by Django 5.0.7 on 2024-09-09 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0004_alter_customer_userobj_monthlyuser_delete_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderdatetime", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.IntegerField()),
                ("totalprice", models.FloatField()),
                ("status", models.CharField(max_length=15)),
                (
                    "itemobj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="newapp.item"
                    ),
                ),
                (
                    "userobj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
