# Generated by Django 5.0.7 on 2024-09-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0005_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monthlyuser",
            name="userobj",
        ),
        migrations.RemoveField(
            model_name="yearlyuser",
            name="userobj",
        ),
        migrations.DeleteModel(
            name="CreditUser",
        ),
        migrations.DeleteModel(
            name="MonthlyUser",
        ),
        migrations.DeleteModel(
            name="YearlyUser",
        ),
    ]
