# Generated by Django 5.0.7 on 2024-09-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0007_credituser_monthlyuser_yearlyuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(default="Received", max_length=15),
        ),
    ]
