# Generated by Django 5.0.7 on 2024-09-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0008_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="itemobj",
        ),
    ]
