# Generated by Django 5.0.7 on 2024-09-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0009_remove_order_itemobj"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
    ]
