# Generated by Django 5.0.7 on 2024-09-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0010_delete_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monthlyuser",
            name="comf_dettol",
        ),
        migrations.RemoveField(
            model_name="yearlyuser",
            name="comf_dettol",
        ),
    ]
