# Generated by Django 5.0.7 on 2024-09-10 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0011_remove_monthlyuser_comf_dettol_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
