# Generated by Django 5.0.7 on 2024-09-10 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0012_delete_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderdatetime", models.DateTimeField(auto_now_add=True)),
                ("clothes", models.IntegerField()),
                ("comfort", models.BooleanField()),
                ("dettol", models.BooleanField()),
                ("iron", models.IntegerField()),
                ("bedspread", models.IntegerField()),
                ("mediumblanket", models.IntegerField()),
                ("largeblanket", models.IntegerField()),
                ("totalprice", models.FloatField()),
                ("status", models.CharField(default="Received", max_length=15)),
                (
                    "userobj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
